#load data base generated by Algorithm 2
setwd()
dataSet <- read.csv()

#define the region length in base-pairs
regionLegth = 1000

numRegion <- ncol(dataSet)
nPatients <- nrow(dataSet)

#create the matrix with the star and stop points for each patient
for (indPatient in 1:nPatients) {
  
  currRegionVal <- dataSet[indPatient,1]
  
  tmpStart <- c()
  tmpStop  <- c()
  
  for (indRegion in 1:numRegion){
    
    if ((currRegionVal == 0) & (dataSet[indPatient,indRegion] == 1)){
      
      #define a starting point
      tmpStart <- c(tmpStart,indRegion*regionLegth)
      
    }
    if ((currRegionVal == 1) & (dataSet[indPatient,indRegion] == 0)){
      #define a stoping point
      tmpStop <- c(tmpStop,indRegion*regionLegth)
    }
    
    currRegionVal <- dataSet[indPatient,indRegion]
    
    if ((currRegionVal == 1) & (indRegion == 1)) {
      
      
      tmpStart <- c(tmpStart,indRegion*regionLegth)
    }
    
    
    if ((currRegionVal == 1) & (indRegion == numRegion)) {
      
      #Catch intervals including last segment
      tmpStop <- c(tmpStop, (indRegion+1)*regionLegth)
      
    }
  }
  
  #create the dataframe with the star and stop pts
  dataPatient <- as.data.frame(cbind(tmpStart,tmpStop))
  
  
  if(is.null(tmpStart) == FALSE) {
    colnames(dataPatient) <- c('start','stop')
    
    write.csv2(dataPatient,sprintf('patient%.3d.csv',indPatient))
  }
  
  #write the file for the patient
  
  
  
}
